# Generated by Django 5.0.7 on 2024-10-06 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="types",
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)"
                    )
                ],
            ),
        ),
    ]
