# Generated by Django 5.0.7 on 2024-10-12 06:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_transaction_types_alter_customer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="loan",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "loan_refno",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8}$", "Account number must be exactly 8 digits."
                            )
                        ],
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("Personal", "Personal"),
                            ("Home", "Home"),
                            ("Car", "Car"),
                            ("Business", "Business"),
                            ("Education", "Education"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("type-1", "1-month/s[10%,1]"),
                            ("type-2", "36-month/s[8%,3]"),
                            ("type-3", "12-month/s[9%,1]"),
                            ("type-4", "24-month/s[8%,2]"),
                        ],
                        max_length=100,
                    ),
                ),
                ("amount", models.FloatField()),
                ("date_applied", models.DateField(null=True)),
                ("date_approved", models.DateField(null=True)),
                ("date_released", models.DateField(null=True)),
                ("date_rejected", models.DateField(null=True)),
                ("loan_status", models.CharField(max_length=120)),
                ("loan_desc", models.TextField(max_length=200)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.accountnumber",
                    ),
                ),
            ],
        ),
    ]
