# Generated by Django 5.0.7 on 2024-10-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_loan_loan_desc_loan_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.accountnumber"
            ),
        ),
        migrations.AlterField(
            model_name="loan_details",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.accountnumber"
            ),
        ),
    ]
