# Generated by Django 5.0.7 on 2024-10-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_loan_account_alter_loan_details_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="plan",
            field=models.CharField(
                choices=[
                    ("1-month/s[10%,1]", "1-month/s[10%,1]"),
                    ("36-month/s[8%,3]", "36-month/s[8%,3]"),
                    ("12-month/s[9%,1]", "12-month/s[9%,1]"),
                    ("24-month/s[8%,2]", "24-month/s[8%,2]"),
                ],
                max_length=100,
            ),
        ),
    ]
