# Generated by Django 5.0.7 on 2024-10-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_loan_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="m_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="pay_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalty",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="tp_amount",
            field=models.FloatField(null=True),
        ),
    ]
