# Generated by Django 5.0.7 on 2024-10-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_loan_due_date_loan_m_amount_loan_pay_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="count",
            field=models.IntegerField(null=True),
        ),
    ]
